language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests -v --with-coverage --cover-package=pyiss
after_success:
  coveralls